lib/node.js

Reverts Zilliqa/Zilliqa-JavaScript-Library#12

Revert "remove check"

---

lib/util.js

Useful util to have. Already tested for correctness.

getAddressFromPublicKey

---

package.json
src/__tests__/util.spec.ts

Just a simple PR to ensure that files are built before being published. This is to avoid potential mistakes.

Add yarn script for easier publishing workflow

---

package.json

fix(): fix published tarball not including type declarations

---

packages/zilliqa-js-account/package.json
packages/zilliqa-js-account/src/wallet.ts
packages/zilliqa-js-account/test/wallet.spec.ts
yarn.lock

Add `Wallet.addByMnemonic`, to support add accounts to wallet with mnemonic

Support add accounts to wallet with mnemonic

---

packages/zilliqa-js-account/src/transaction.ts
packages/zilliqa-js-account/src/util.ts

Calculate delay between each attempt with:
`const delay = Math.random() * (Math.pow(2, attempt) * 60)`

Exponential back off for Transaction.prototype.confirm

---

lerna.json
packages/zilliqa-js-account/package.json
packages/zilliqa-js-blockchain/package.json
packages/zilliqa-js-contract/package.json
packages/zilliqa-js-core/package.json
packages/zilliqa-js-crypto/package.json
packages/zilliqa-js-proto/package.json
packages/zilliqa-js-util/package.json
packages/zilliqa/package.json

chore(release): publish 0.2.3

---

.gitignore
jest-framework-setup.js
jest.config.js
jest.iconfig.js
packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-blockchain/src/types.ts
packages/zilliqa-js-blockchain/test/chain.ispec.ts
packages/zilliqa-js-core/src/net.ts

This implements the necessary JS APIs for https://github.com/Zilliqa/Zilliqa/pull/877

feat(chain): add new API methods and update interfaces

---

packages/zilliqa-js-contract/src/types.ts
packages/zilliqa-js-contract/test/contract.spec.ts

fix(contract): fix broken typings

---

README.md

Fix broken lernajs link in readme

chore(readme): fix broken lernajs link

---

README.md
packages/zilliqa-js-blockchain/README.md
packages/zilliqa-js-blockchain/src/util.ts
packages/zilliqa-js-contract/README.md
packages/zilliqa-js-contract/package.json
packages/zilliqa-js-contract/src/types.ts
packages/zilliqa-js-contract/test/contract.ispec.ts
packages/zilliqa-js-contract/test/test.abi.ts
tslint.json

* Added `code` and `data` to transaction object
* Removed typings for `getSmartContractState` to make it compatible with post-IPC upgrade
Note: This is the first release of alpha version for community feedback
install this alpha patch through NPM and test

0.8.0-alpha-1

---

README.md

Fix example quickstart code on README.md
Problems building sample as discussed with @renlulu here and on discord. This PR should provide a solution such as the example code runs without errors.
#164 -  removed unnecessary 0x from address
#165 #168 - assign newly deployed contract to another object and use this when checking state
#167 - Perhaps not a problem for all but added to installation advice for now
Also as discussed on discord:
- running with provided PK seemed to timeout - recommended setting own testnet PK with instructions how to generate and fund wallet
- generate a time-based message to update contract so it can be run several times
- log various parts of program to console (send tx, deploy contract, update contract, get state)
- Corrected other minor typos where seen
Review …

Update example code and minor typos

---

packages/zilliqa-js-contract/src/contract.ts

Store error message while sending transaction.

fix(contract): store error message while preparing transaction

---

packages/zilliqa-js-contract/src/contract.ts

This PR shows more helpful error messages. 
e.g., 
```
{ 
code: -8,
data: null,
message: 'Gas limit (10000) lower than minimum for creating contract (50)' 
}
```

feat(contract): reject with error message

---

examples/deployContract.js
packages/zilliqa-js-contract/src/contract.ts
packages/zilliqa-js-contract/test/contract.spec.ts

Add method to let users deploy contract without confirming immediately.

feat(contract): deploy without confirming, and example

---

examples/queryTransaction.js
packages/zilliqa-js-blockchain/test/chain.spec.ts
packages/zilliqa-js-core/src/types.ts

Record transition array inside transaction receipt, try to fix #192. Add an example js file as well.

feat(receipt): add data struct transition array into transaction receipt

---

packages/zilliqa-js-account/test/transaction.spec.ts
packages/zilliqa-js-crypto/src/util.ts

One very small update on error message, to be consistent with API documentation.

chore: update one error msg

---

packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-core/src/net.ts

Implement rpc method [GetTotalCoinSupply](https://apidocs.zilliqa.com/#gettotalcoinsupply).

feat(blockchain): impl getTotalCoinSupply rpc method

---

examples/getTxnBodiesForTxBlock.js
packages/zilliqa-js-blockchain/README.md
packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-blockchain/test/chain.spec.ts
packages/zilliqa-js-core/src/net.ts

This pr is to support new API GetTxnBodiesForTxBlock. 
1. Run unit tests.
2. Run examples/getTxnBodiesForTxBlock.js

feat(blockchain): support api GetTxnBodiesForTxBlock

---

packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-blockchain/test/chain.spec.ts
packages/zilliqa-js-core/src/net.ts
packages/zilliqa-js-core/src/types.ts

To support api GetPendingTxns.
1. Run unit test.
2. Run
```
const { Zilliqa } = require('@zilliqa-js/zilliqa');
const zilliqa = new Zilliqa('https://api.zilliqa.com');
async function test() {
try {
const tx = await zilliqa.blockchain.getPendingTxns();
console.log(tx.result.Txns);
} catch (e) {
console.log(e);
}
}
test();
```

feat(blockchain): support api GetPendingTxns

---

packages/zilliqa-js-account/src/wallet.ts
packages/zilliqa-js-account/test/transaction.spec.ts
packages/zilliqa-js-account/test/wallet.spec.ts
packages/zilliqa-js-blockchain/test/chain.spec.ts
packages/zilliqa-js-contract/test/contract.spec.ts

This PR is to add checking function before sending transactions out (during signing process), in case uses don't have sufficient funds.
1. Run unit tests

feat: check funds during signing

---

.github/CODEOWNERS

Update Github code owner to reflect the current team member maintaining ZilliqaJS

Update github code owner

---

packages/zilliqa-js-util/src/validation.ts

fix: is bech32 format

---

packages/zilliqa-js-crypto/src/util.ts

This tiny PR is to fix the issue during the conversion from public key to address.

fix(util): normalized pubkey

---

packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-blockchain/src/util.ts

1. For `getTransaction`, can run script:
```
const { Zilliqa } = require('@zilliqa-js/zilliqa');
const zilliqa = new Zilliqa('https://dev-api.zilliqa.com');
async function test() {
try {
const tx = await zilliqa.blockchain.getTransaction(
'4fbcb7fd7d154017b7b12d028fa8dfd0d810a7e235450413ac2f4c0a35766d3b',
);
console.log(JSON.stringify(tx));
} catch (e) {
console.log(e);
}
}
test();
```
2. For `getSmartContracts`, can run script:
```
const { Zilliqa } = require('@zilliqa-js/zilliqa');
const zilliqa = new Zilliqa('https://dev-api.zilliqa.com');
async function test() {
try {
const contracts = await zilliqa.blockchain.getSmartContracts(
'dFD64AeB30C9025f08C9925E2bD528449b8621b0',
);
console.log(JSON.stringify(contracts));
} catch (e) {
console.log(e);
}
}
test();
```
3. Run unit tests

Fix getTransaction and getSmartContracts

---

README.md

update readme to include zilliqa-js/viewblock

update readme to include zilliqa-js/viewblock

---

.gitmodules

Add viewblock Zilliqa-js package as submodule

Add submodule viewblock

---

.gitmodules

Reverts Zilliqa/Zilliqa-JavaScript-Library#235

Revert "Add submodule viewblock"

---

.npmignore
jest.config.js
package.json
packages/zilliqa-js-viewblock/README.md
scripts/bundle.ts

Add readme for viewblock package

Add viewblock api readme

---

README.md

Add link to viewblock api readme on main readme

Add link to viewblock api readme on main readme

---

examples/callContract.js
examples/createTransactionRaw.js
examples/deployContract.js
examples/helloWord.js
packages/zilliqa-js-crypto/package.json
packages/zilliqa-js-crypto/src/random.ts
yarn.lock

To use sodium generate random bytes.
Run scripts inside examples folder.

feat: use sodium to generate random bytes

---

packages/zilliqa-js-core/src/types.ts

1. Add new field `TxnFees` to tx block header.
2. Update status type of pending transaction.

fix: add TxnFees into block header, update pending status of txns

---

packages/zilliqa-js-blockchain/src/chain.ts

Update pending codes according to `https://github.com/Zilliqa/dev-docs/pull/111/files`

fix: pending codes

---

packages/zilliqa-js-crypto/README.md

fix: README for getPubKeyFromPrivateKey()

---

README.md
examples/node/createTransactionRaw.js
examples/node/helloWord.js
examples/node/walletSign.js
examples/webpack/html/index.js
examples/webpack/react/src/App.js
packages/zilliqa-js-blockchain/test/chain.ispec.ts
packages/zilliqa-js-contract/test/contract.ispec.ts

Adjust gas price to 2000 Li (past upgrade)
Adjust gas limit for payment transaction to 50 (next upgrade)

chore: Update gas price and gas limit

---

.github/CODEOWNERS

chore: add noel to code owner

---

packages/zilliqa-js-core/src/types.ts

This PR fixes the type issue from #316 
References:
- https://dev.zilliqa.com/docs/dev/dev-txn-receipt

fix(core): tx receipt type

---

scripts/bundle.ts
scripts/publish.ts
scripts/schema.ts
typings/elliptic.d.ts

This PR removes the unused import.

refactor: remove unused import

---

.npmignore
README.md
jest.config.js
package.json
packages/zilliqa-js-viewblock/README.md
scripts/bundle.ts

This PR removes the empty viewblock package. In this way, we can reduce complexity for test and bundling config.

feat: remove viewblock package

---

.github/PULL_REQUEST_TEMPLATE.md

This PR updates the PR template so that a requester can provide details in a easier and more structured way.

docs: pr tempate

---

package.json
yarn.lock

This PR upgrades typescript version `v3.2` -> `v3.9.10`
`yarn bootstrap` gives us the same output.

build: typescript v3.2 -> v3.9.10

---

package.json

This PR fixes https://github.com/Zilliqa/Zilliqa-JavaScript-Library/issues/331 by whitelisting the production files and reducing the unpacked size from `5.3 MB` to `708.5 kB` (87% reduction).
You can run `npm publish --dry-run` to test it.
https://docs.npmjs.com/cli/v7/commands/npm-publish#dry-run
Note that you need to use npm `v7`.
Without whitelisting
```                                        
npm notice package size:  1.5 MB                                  
npm notice unpacked size: 5.3 MB                                  
npm notice shasum:        8db0918e89b65e23aba81c3047f3b83a3b700556
npm notice integrity:     sha512-wbP+UrDG7zCXb[...]w98Xrt+sclRfw==
npm notice total files:   495  
```
With whitelisting
```                                             
npm notice === Tarball …
```

build(npm): whitelist production files

---

packages/zilliqa-js-blockchain/src/chain.ts

This PR removes unnecessary or outdated comments which are
- the redundant details you can find in https://dev.zilliqa.com/docs/apis/api-introduction.
- parameter and return types which are self-explanatory with TypeScript.
In this way, we can manage the documentation and code in more consistent and easier way. Otherwise, we will have to update documents in multiple places by doing many copy-and-paste.

refactor(blockchain): comments

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

As part of the issue template, tips and hints are added to guide the user along the creation process. 
However, the tips are not commented out and it pollutes the issue report itself
This PR comments out the tips.

comment out issues templates tips and hints

---

package.json
packages/zilliqa-js-crypto/test/tsconfig.json

This PR fixes the following error:
> File '.../Zilliqa-JavaScript-Library/packages/zilliqa-js-crypto/test/schnorr.fixtures.json' is not listed within the file list of project '/.../Zilliqa-JavaScript-Library/packages/zilliqa-js-crypto/test/tsconfig.json'. Projects must list all files or use an 'include' pattern.ts(6307)
Also, this PR uses jest verbose flag.

fix(tsconfig): use include pattern

---

package.json

This PR adds `prepare` script to install husky since [husky doesn't autoinstall anymore](https://blog.typicode.com/husky-git-hooks-autoinstall/).

fix: install husky with prepare script

---

README.md
package.json

This PR documents how to use verdaccio with `yarn release:local`. 
Previously, We didn't simulate a publish.

Use Verdaccio

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.prettierignore
.prettierrc
README.md
package.json
packages/zilliqa-js-account/README.md
packages/zilliqa-js-account/test/tsconfig.json
packages/zilliqa-js-account/tsconfig.json
packages/zilliqa-js-account/tsconfig.test.json
packages/zilliqa-js-contract/README.md
packages/zilliqa-js-core/README.md
packages/zilliqa-js-core/test/tsconfig.json
packages/zilliqa-js-crypto/README.md
packages/zilliqa-js-crypto/test/tsconfig.json
packages/zilliqa-js-crypto/tsconfig.json
packages/zilliqa-js-crypto/tsconfig.test.json
packages/zilliqa-js-proto/README.md
packages/zilliqa-js-util/README.md
tsconfig.test.json

This PR formats json and markdown files with prettier config change.
Previously, Prettier have ignored json and markdown files.

Format json, markdown files

---

README.md

This PR explains how to install private packages.

docs: how to install private packages

---

examples/README.md

This PR adds a notice for [examples](https://github.com/Zilliqa/Zilliqa-JavaScript-Library-Examples)

docs: examples notice

---

packages/zilliqa-js-subscriptions/package.json

This PR sets `mock-socket` as dev dependency since it's for testing.

build(subscription): mock-socket as dev dep

---

.prettierignore

This PR ignores `lerna.json` for formatting by prettier.

chore: ignore lerna.json for formatting

---

packages/zilliqa-js-contract/README.md

This PR closes #366 by removing the outdated warnings only.

docs(contract): remove outdated warning

---

packages/zilliqa-js-account/package.json
packages/zilliqa-js-blockchain/package.json
packages/zilliqa-js-contract/package.json
packages/zilliqa-js-core/package.json
packages/zilliqa-js-crypto/package.json
packages/zilliqa-js-proto/package.json
packages/zilliqa-js-subscriptions/package.json
packages/zilliqa-js-util/package.json
packages/zilliqa/package.json
tsconfig.base.json

This PR fixes the `yarn clean` which has been broken since https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/327.
> TypeScript 3.4 introduces a new flag called --incremental which tells TypeScript to save information about the project graph from the last compilation. The next time TypeScript is invoked with --incremental, it will use that information to detect the least costly way to type-check and emit changes to your project.
TypeScript 3.4 introduced [--incremental](https://www.typescriptlang.org/tsconfig/#incremental) and it is set to `true` by default when [--composite](https://www.typescriptlang.org/tsconfig/#composite) is `true` which is [the our case](https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/tsconfig.base.json#L5). 
Therefore,`tsconfig.tsbuildinfo` …

fix: cleanup tsbuildinfo

---

packages/zilliqa-js-core/src/types.ts

This PR fixes `GasPrice` type in `DsBlockHeader` (`number` -> `string`).
```json
{
"id": "1",
"jsonrpc": "2.0",
"result": {
"header": {
"BlockNum": "5898",
"Difficulty": 91,
"DifficultyDS": 149,
"GasPrice": "1000000000",
"LeaderPubKey": "0x026964CBF00EE542F5CBE80395FFEA747227BC3EFCC21D04956380180A9BE21546",
"PoWWinners": [
"0x0219DB403A630022EE014AFD97D02E2DBC6BCEED2506A9E57B5EE5D9EA4F154929",
"0x02D9C8FC6C87891968ECCEE5EF1CD8A9F8FC32C6463F2FE4E846DFD5C5F45A625E",
"0x02E07F03C71D26433E7F290416FA43374DA72704F8AA973D4771AA763ACD7C509C",
"0x02E0FB6CDAEA57738959B493652A74E86339AF2CFE998FB7424BBD7A813450743F",
"0x0315E9B13D5A5D29902F1EECE0933E96A0AF9939853D5F82B438AAED9F7560B3FC",
"0x034D9B1B0DC80A0103AE7826886B415C29BF3E814FF6720F6C9C47B57589EFEAAA", …
```

fix(core): ds block header type

---

packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-blockchain/test/chain.spec.ts

This PR checks the negative integer as tx block number input for GetStateProof.

feat: validate txblock for getStateProof

---

packages/zilliqa-js-crypto/src/random.ts
packages/zilliqa-js-crypto/test/random.browser.spec.ts
packages/zilliqa-js-crypto/test/random.node.spec.ts
packages/zilliqa-js-crypto/test/random.worker.spec.ts

This PR checks environments and includes tests for node.js, browser, and web worker.

refactor(crypto): random

---

packages/zilliqa-js-blockchain/src/chain.ts
packages/zilliqa-js-blockchain/test/chain.spec.ts
packages/zilliqa-js-core/src/net.ts

This PR closes #395 by supporting [GetTransactionsForTxBlockEx](https://dev.zilliqa.com/docs/apis/api-transaction-get-txs-for-txblock-ex) and [GetTxnBodiesForTxBlockEx](https://dev.zilliqa.com/docs/apis/api-transaction-get-txbodies-for-txblock-ex).

Feat/support api v7.2.0

---

README.md
package.json
packages/zilliqa-js-account/package.json
packages/zilliqa-js-blockchain/package.json
packages/zilliqa-js-contract/package.json
packages/zilliqa-js-core/package.json
packages/zilliqa-js-crypto/package.json
packages/zilliqa-js-subscriptions/package.json
packages/zilliqa-js-util/package.json
packages/zilliqa/package.json
scripts/bundle.ts
yarn.lock

This PR adds `tslib` as dependency. 
As of TypeScript 3.9, tslib version of 2.x is required to build new applications.
> The tslib is a runtime library for Typescript. The version of this library is bound to the version of the TypeScript compiler used to compile a library. Peer dependencies do not accurately represent this relationship between the runtime and the compiler.
https://angular.io/guide/migration-update-libraries-tslib#why-is-this-migration-necessary
Users have been asked to install `tslib` since https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/169.
```
yarn add @zilliqa-js/zilliqa
yarn add tslib
yarn add bn.js
```
References: 
- https://github.com/Zilliqa/Zilliqa-JavaScript-Library/issues/167
- https://github.com/angular/angular/blob/master/packages/core/package.json …

build: tslib as dependency

---

README.md

This PR updates installation part in README.md.

docs: installation

---

packages/zilliqa-js-crypto/src/random.ts

This PR converts a buffer to a hex string in a simpler way.
```
const b = require('crypto').randomBytes(16)
console.log(b)
// <Buffer 06 6e d5 0e 66 b2 9b 6e a6 b2 0b 21 ff de a7 17>
const hexStr = b.toString('hex')
console.log(hexStr)
// 066ed50e66b29b6ea6b20b21ffdea717
```
https://nodejs.org/api/buffer.html
> The Buffer class is a subclass of JavaScript's Uint8Array class and extends it with methods that cover additional use cases. Node.js APIs accept plain Uint8Arrays wherever Buffers are supported as well.

refactor(crypto): hex

---

packages/zilliqa-js-crypto/src/random.ts

This PR checks if the global variable `process` exists.

fix: check global var process

---

packages/zilliqa-js-account/src/transaction.ts

fix payload getter
Payload getter has hardcoded version 0

payload getter has version: 0

---

.travis.yml
README.md
tasks/tsc.sh

This PR uses [the new codecov uploader](https://docs.codecov.com/docs/codecov-uploader).
https://www.npmjs.com/package/codecov is being deprecated (February 1, 2022).
> This uploader is being deprecated by the Codecov team. We recommend migrating to our new uploader as soon as possible to prevent any lapses in coverage. The new uploader is open source, and we highly encourage submitting Issues and Pull Requests.
>
> You can visit our blog post to learn more about our deprecation plan
>
> On February 1, 2022 this uploader will be completely deprecated and will no longer be able to upload coverage to Codecov.

ci: codecov

---

package.json
packages/zilliqa-js-account/package.json
packages/zilliqa-js-blockchain/package.json
packages/zilliqa-js-contract/package.json
packages/zilliqa-js-core/package.json
packages/zilliqa-js-crypto/package.json
packages/zilliqa-js-proto/package.json
packages/zilliqa-js-util/package.json
packages/zilliqa/package.json

This PR removes `author` field per package.json.

chore: remove author

---

README.md

This PR uses `main` branch for the badges.

docs: badges with main branch

---

README.md

This PR fixes the link of the travis badge.

docs: fix travis badge

---

lerna.json
tasks/local-registry.sh

This PR updates the allowed branchs (`main` and `e2e`) in lerna.json.

chore: update allowed branches

---

README.md

This PR updates the quick start section.

docs: dev wallet, zil faucet
