Zilliqa/zilliqa-js

- gulpfile.js
- index.js
- lib/node.js
- lib/zilliqa.js
Let's use `const` or `let` instead of `var` to declare variables to avoid polluting the global namespace. 
for details: https://hackernoon.com/js-var-let-or-const-67e51dbb716f
> Use const instead of var

- lib/schnorr.js
This PR removes unnecessary strict mode directive.
ES6 module code, which Babel expects by default, is automatically Strict Mode according to the ES6 spec.
For details: https://eslint.org/docs/rules/strict
Still we get build output like this:
zilliqa.min.js
``` javascript
(...) ({1:[function(e,t,r){"use strict";var i=e("./lib/zilliqa");"undefined"!=typeof window&&void 0===window.Zilliqa&&(window.Zilliqa=i),t.exports={Zilliqa:i}},{"./lib/zilliqa":6}],2:[function(e,t,r){t.exports={version:"0.0.1",defaultNodeUrl:"http://localhost:4201"}},{}],3:[function(e,t,r){"use strict";function i(e){u(e,{url:[c.isUrl]}),this.url=e.url,this.apiUrl="https://api.zilliqa.com"} (...)
```
> Remove unnecessary strict mode directive

- README.md
GetSmartContracts uses `getSmartContracts` instead of `getSmartContractState`
> typos in readme.md

- lib/schnorr.js
This PR declares `const` instead of `let` only for those variables never reassigned. By doing so, readers can figure out which variables are reassigned. Therefore, it reduces cognitive load for readers and improves maintainability. 
For details: https://eslint.org/docs/rules/prefer-const
> Use const if never reassigned

- README.md
- package.json
- src/__tests__/util.spec.ts
- src/node.ts
- src/schnorr.ts
- src/util.ts
As noted in commit ca0b799f7f20787c6e69db91d868cef9eef27be3, we are temporarily casting `amount` from `BN` to `number` until such time as https://github.com/Zilliqa/Zilliqa/issues/524 is resolved.
@AmritKumar @edisonljh
> Cast `amount` to `number`

- src/__tests__/util.spec.ts
- src/util.ts
This PR replaces all `new Buffer` _which is deprecated and unsafe_ with `Buffer.from`
We should not use deprecated/unsafe Buffer constructor.
The behavior of new Buffer() is different depending on the type of the first argument, security and reliability issues can be inadvertently introduced into applications when argument validation or Buffer initialization is not performed.
To make the creation of Buffer instances more reliable and less error-prone, the various forms of the new Buffer() constructor have been deprecated and replaced by separate Buffer.from(), Buffer.alloc(), and Buffer.allocUnsafe() methods.
Check this out: https://nodejs.org/api/buffer.html#buffer_buffer_from_buffer_alloc_and_buffer_allocunsafe
> new Buffer is deprecated and unsafe

- src/util.ts
This PR replaces all double equals with triple equals.
(`!=` or `==`)  =>   (`!==` or `===`)
It is considered good practice to use the type-safe equality operators === and !== instead of their regular counterparts == and !=. The reason for this is that == and != do type coercion which follows the rather obscure Abstract Equality Comparison Algorithm. For instance, the following statements are all considered true:
* [] == false
* [] == ![]
* 3 == "03"
If one of those occurs in an innocent-looking statement such as a == b the actual problem is very difficult to spot.
Check this out: https://eslint.org/docs/rules/eqeqeq
> Use triple equals instead of double equals

- package.json
- webpack.config.js
- yarn.lock
This fixes `fetch` for node.js users by bundling the polyfill in the build output.
> fix(build): fix fetch polyfill in node.js environment

- packages/zilliqa-js-account/package.json
- packages/zilliqa-js-account/test/account.spec.ts
- packages/zilliqa-js-account/test/fixtures/gen-keystores.ts
- packages/zilliqa-js-account/test/fixtures/keystores.json
- packages/zilliqa-js-crypto/src/keystore.ts
- packages/zilliqa-js-crypto/src/types.ts
- typings/pbkdf2.d.ts
- yarn.lock
* Generate keystore test vectors with web3.js and test against them
* Fixed several bugs to make the tests pass
The script using to generate test vectors with web3.js is included at `zilliqa-js-account/test/fixtures/gen-keystores.ts`
> Generate keystore test vectors with web3.js and test against them

- packages/zilliqa-js-contract/test/contract.ispec.ts
- packages/zilliqa-js-contract/test/fixtures.ts
This PR adds an additional test to ensure that the network performs as expected even after a failed contract deployment transaction. This is because we had observed transactions failing after the `touch and pay` contract was deployed without any `data` property.
Run the tests, possibly monitor logs on network side.
> test(contract): add additional contract integration tests

- packages/zilliqa-js-account/src/transaction.ts
- packages/zilliqa-js-account/src/util.ts
- packages/zilliqa-js-account/src/wallet.ts
- packages/zilliqa-js-account/test/account.spec.ts
- packages/zilliqa-js-account/test/fixtures/keystores.json
- packages/zilliqa-js-account/test/transaction.spec.ts
- packages/zilliqa-js-account/test/transactionFactory.spec.ts
- packages/zilliqa-js-account/test/wallet.spec.ts
- packages/zilliqa-js-blockchain/src/chain.ts
- packages/zilliqa-js-blockchain/test/chain.ispec.ts
- packages/zilliqa-js-contract/src/contract.ts
- packages/zilliqa-js-contract/src/factory.ts
- packages/zilliqa-js-contract/test/contract.ispec.ts
- packages/zilliqa-js-contract/test/contract.spec.ts
- packages/zilliqa-js-crypto/src/util.ts
- packages/zilliqa-js-crypto/test/address.spec.ts
- packages/zilliqa-js-crypto/test/keys.spec.ts
This PR is related to #120, where the new `bech32` address format was added. This diff goes one step further by ensuring that any transaction-creating logic is always forced to use a `toAddr` that is either:
i) valid bech32
ii) valid Zilliqa checksum
The purpose of doing this is to make sure all wallets, explorers, and dApps prevent users from sending transactions of native ZIL to Ethereum addresses leading to irrecoverable loss. Other SDKs should use this as an reference implementation, **icluding all relevant unit tests.**
> fix: force `toAddr` to be either checksum or bech32

- packages/zilliqa-js-blockchain/package.json
- packages/zilliqa-js-blockchain/src/util.ts
- packages/zilliqa-js-blockchain/test/util.spec.ts
This fixes an issue where calls to `zilliqa.blockchain.getTransaction(...)` were failing as transactions cannot be constructed with non-checksummed addresses (returned from the RPC API).
> fix(chain): fix getTransaction failing to construct a Transaction object

- packages/zilliqa-js-account/src/account.ts
- packages/zilliqa-js-blockchain/src/chain.ts
Addresses can be really confusing for a developer. It can come in ByStr20 or `bech32` format. If it comes in `ByStr20`, it might or might not come with a `0x` prefix.
This PR adds the following:
- Strips `0x` before sending to RPC
- Converts `bech32` to `ByStr20` before sending to the RPC
- Added `bech32` to Account object
Fixes #148 and #149 
CC: @neeboo
> More support for bech32 formats

- packages/zilliqa-js-contract/test/contract.spec.ts
Currently, the Travis CI build is failing since this [build](https://travis-ci.com/Zilliqa/Zilliqa-JavaScript-Library/builds/117238731)
This PR fixes the type error from `contract.spec.ts`.
> fix: contract spec

- README.md
Currently, the Travis build badge in README.md can be misleading because it shows the status of `branch=feature/monorepo` instead of `branch=dev`
Hence, This PR updates the URL of the build badge.
> docs(README.md): update travis badge url

- packages/zilliqa-js-account/src/account.ts
To normalize private key added to Wallet and Account
To ensure the publicKey and address generated are the same
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/issues/157
```javascript
const key1='aaaaaa...'
const key2=`0x${key1}`
const account1=new Account(key1);
const account2=new Account(key2);
console.log(account1.privateKey===account2.privateKey)
console.log(account1.publicKey===account2.publicKey)
console.log(account1.address===account2.address)
```
> feat(account):add normalizePrivateKey

- packages/zilliqa-js-crypto/package.json
- yarn.lock
resolves #166 
This is a hotfix for #166 
`scrypt` [is not maintained anymore](https://github.com/barrysteyn/node-scrypt/issues/193) and is incompatible with Node v0.12.x.
[scrypt.js](https://github.com/axic/scrypt.js) is just a thin wrapper around `scrypt` (native code) with a fallback to `scryptsy` (pure JS): https://github.com/axic/scrypt.js/blob/master/index.js#L4
The _quick & dirty_ fix could be the following:
Add `scryptsy` as an explicit dependency of the `zilliqa-js-crypto` and make `scrypt.js` an optional dependency. 
The next step could be to do something similar to https://github.com/michaelsbradleyjr/web3.js/blob/d7adf702f815537376e7b8adb8fbdacfece17435/packages/web3-eth-accounts/src/scrypt.js
Please note that it is a "quick & dirty" solution until we adopt a more appropriate …
> fix(crypto): make scrypt.js an optional depedency

- packages/zilliqa-js-blockchain/src/chain.ts
Create a function to let users send transaction without waiting for the confirm.
> feat(blockchain): create transaction without confirm

- examples/helloWord.js
- packages/zilliqa-js-blockchain/src/chain.ts
- packages/zilliqa-js-core/src/net.ts
- packages/zilliqa-js-core/src/types.ts
Add support for checking transaction's pending status:
```
const response  = await zilliqa.blockchain.getPendingTxn('0x2cf109b25f2132c08a4248e2be8add6b95b92aef5b2c77e737faefbc9353ee7c');
console.log(response.result);
```
The result could be:
```
{ code: 0,
confirmed: true,
info: 'Txn already processed and confirmed' }
```
or something else similar
```
{ code: 1,
confirmed: false,
info: 'Nonce too high' }
```
> feat(core): add penging transaction support

- packages/zilliqa-js-crypto/src/bech32.ts
- packages/zilliqa-js-util/src/validation.ts
Since we have network id, actually we don't need parameter `testnet` to distinguish different networks while doing bech32 conversion. In other works, `testnet` and `mainnet` can share only one standard on address format.
> fix: remote paramter testnet while doing bech32 conversion

- packages/zilliqa-js-account/test/transaction.spec.ts
- packages/zilliqa-js-crypto/src/util.ts
To force user to use checksum address or bech32 address while doing payment transaction
> chore: force to use bech32 for checksum address

- README.md
The default time interval is set to `1000` in the SDK. However, in the readme example, it was set to `100`, which will be too short and will hit the time limit before the transaction gets confirm in the block.
> chore(readme): change time from 100 to 1000

- packages/zilliqa-js-account/src/wallet.ts
The overall goals of this pull request is to fix sign procedure once user pass `nonce` explicitly. Currently situation is, if user pass `nonce` while constructing transaction object, the field `pubKey` will be missed.
> fix(account): fix sign error with nonce being passed explicitly

- examples/callContract.js
- packages/zilliqa-js-contract/src/contract.ts
- packages/zilliqa-js-contract/test/contract.spec.ts
To separate confirming procedure from contract calling. Similar to `deployWithoutConfirm` or `createTransactionWithoutConfirm`, in other words, people can get transaction id immediately then process waiting for confirmation later. Also add unit test and example script.
> feat(contract): support calling contract without confirming

- packages/zilliqa-js-account/src/wallet.ts
Provide a wallet method to add account based on a mnemonic phrase, but compatible with Ledger.
The key derivation  used in the Ledger app is different from the one used by other wallets. To enable recovery of Ledger wallets based on their mnemonic phrase in non Ledger wallets, this method is now provided.
> Provide addByMnemonicLedger() for derivation path used in Ledger

- README.md
- packages/zilliqa-js-crypto/package.json
- packages/zilliqa-js-crypto/src/random.ts
- yarn.lock
This pr replaces the [`node-sodium`](https://github.com/paixaop/node-sodium) package  with [`sodium-native`](https://github.com/sodium-friends/sodium-native). The current `node-sodium` package compiles and builds from source during package install. 
This poses an issue on Windows based machines as it requires the users to install Visual Studio Build tools (about 3~5GB) for `node-gyp` library to build the `sodium` package. This further creates inconvenience to users who attempts to incorporate ZilliqaJS into a Docker image.
This pr uses `sodium-native`, a wrapper around [`libsodium`](https://github.com/jedisct1/libsodium) which is `sodium`  compiled to WebAssembly and pure JavaScript and is recommended from https://doc.libsodium.org/bindings_for_other_languages. 
How to use …
> change node-sodium to sodium-native

- .travis.yml
deprecate node 10 from travis build because it is EOL
> removed node 10 support from build matrix

- .prettierignore
This PR makes prettier ignore dist when formatting. 
Otherwise, prettier will try to format dist which can be generated by `yarn bootstrap`.
> chore: ignore dist for formatting

- .eslintrc.js
- packages/zilliqa-js-contract/test/contract.ispec.ts
- packages/zilliqa-js-util/src/validation.ts
This PR uses ESLint [no-unreachable](https://eslint.org/docs/rules/no-unreachable) rule and removes the unreachable codes.
> ESLint no-unreachable 

- package.json
- yarn.lock
This PR adds `tslib` as dev dependency.
In near future, we should upgrade typescript `3.2` -> `4.3` to leverage new features in v4.
However, with typescript 4.3.5, `yarn bootstrap` throws the following error.
```
packages/zilliqa-js-core/src/decorators/sign.ts:45:42 - error TS2343: This syntax requires an imported helper named '__spreadArray' which does not exist in 'tslib'. Consider upgrading your version of 'tslib'.
45       return original.call(this, signed, ...args);
~~~~~~~
```
> build: add tslib as dev dependency

- packages/zilliqa-js-account/src/util.ts
- packages/zilliqa-js-core/src/eventEmitter.ts
- packages/zilliqa-js-core/src/net.ts
This PR fixes typescript errors for Promise resolve and HeadersInit.
References:
```
/**
* Creates a new Promise.
* @param executor A callback used to initialize the promise. This callback is passed two arguments:
* a resolve callback used to resolve the promise with a value or the result of another promise,
* and a reject callback used to reject the promise with a provided reason or error.
*/
new <T>(executor: (resolve: (value: T | PromiseLike<T>) => void, reject: (reason?: any) => void) => void): Promise<T>;
```
```
headers?: HeadersInit;
/**
* A cryptographic hash of the resource to be fetched by request. Sets request's integrity.
*/
```
> Fix Promise resolve & HeadersInit type

- packages/zilliqa-js-account/src/wallet.ts
This PR replaces 'GetBalance' with `RPCMethod.GetBalance`.
> refactor: no hardcoding

- jest-setup.js
- packages/zilliqa-js-crypto/README.md
- packages/zilliqa-js-crypto/src/random.ts
- yarn.lock
This PR changes removes `@trust/webcrypto` because of the following reasons:
- We want to use `sodium-native` to generates bytes safely https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/251
- `@trust/webcrypto` is [no longer maintained](https://github.com/anvilresearch/webcrypto#notice)
> feat: use sodium-native only

- package.json
This PR removes `@trust/webcrypto` from package.json which is an unused dependency and should've been removed from https://github.com/Zilliqa/Zilliqa-JavaScript-Library/commit/b2204bcd5db68a8ac7d010afb0fb9faa1be49a8f
> build: remove @trust/webcrypto

- packages/zilliqa-js-crypto/README.md
- packages/zilliqa-js-crypto/package.json
- packages/zilliqa-js-crypto/src/random.ts
- packages/zilliqa-js-crypto/yarn.lock
- yarn.lock
By using [sodium-universal](https://github.com/sodium-friends/sodium-universal), this PR fixes an issue which occurs when `randomBytes` function is executed in the browsers.
> Universal wrapper for sodium-javascript and sodium-native working in Node.js and the Browser
> Use sodium-universal instead of sodium-native

- packages/zilliqa-js-core/package.json
- yarn.lock
This PR fixes #346 by using cross-fetch v2.2.5 which upgrades node-fetch to version 2.6.1
References:
- https://snyk.io/vuln/SNYK-JS-NODEFETCH-674311
- https://www.npmjs.com/package/cross-fetch/v/2.2.5
> Use cross-fetch v2.2.5

- .husky/pre-commit
- package.json
- yarn.lock
This PR runs `yarn validate` with `pre-commit` hook. `yarn validate` checks formatting and linting.
Therefore, you can validate changelist whenever you commit.
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/runs/3346837441 failed because of lint error.
We can fail earlier and save resources by validating changes with pre-commit hook.
> Validate commit with pre-commit hook

- packages/zilliqa-js-blockchain/src/chain.ts
Zilliqa  JSON RPC is inconsistent. No one would ever guess that `getTransactionStatus` method suppose to accept `txHash` argument without `0x` prefix. Made it indifferent to the prefix.
> Make getTransactionStatus argument format somewhat intuitive

- jest-setup.js
- package.json
- packages/zilliqa-js-account/test/transaction.spec.ts
- packages/zilliqa-js-account/test/transactionFactory.spec.ts
- packages/zilliqa-js-account/test/wallet.spec.ts
- packages/zilliqa-js-blockchain/test/chain.spec.ts
- packages/zilliqa-js-contract/test/contract.spec.ts
- packages/zilliqa-js-core/test/provider.spec.ts
- yarn.lock
This PR uses jest-fetch-mock v3 and adds MockParams for [mockResponses](https://github.com/jefflau/jest-fetch-mock#mocking-multiple-fetches-with-fetchmockresponses)
> Use jest-fetch-mock v3

- package.json
- yarn.lock
This PR removes
- `protobufjs` as it was was added with https://github.com/Zilliqa/Zilliqa-JavaScript-Library/commit/dc7c611d73183f7eb0971ea9c20cfb23bba81e36 and moved into its own package with https://github.com/Zilliqa/Zilliqa-JavaScript-Library/commit/f75d0
- `rollup-plugin-node-builtins` which is not used in `bundle.ts` unlike other plugins.
> Remove unused deps

- package.json
This PR includes `yarn bootstrap && yarn test` in `yarn validate` which runs with pre-commit hook. 
Now it makes sense to include `yarn bootstrap && yarn test` in `yarn validate`. Because testing duration is much shorter than before (89s -> 19s) since https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/361.
> chore: pre-commit hook includes testing

- package.json
- packages/zilliqa-js-account/package.json
- packages/zilliqa-js-blockchain/package.json
- packages/zilliqa-js-contract/package.json
- packages/zilliqa-js-core/package.json
- packages/zilliqa-js-crypto/package.json
- packages/zilliqa-js-proto/package.json
- packages/zilliqa-js-subscriptions/package.json
- packages/zilliqa-js-util/package.json
- packages/zilliqa/package.json
This PR fixes https://github.com/Zilliqa/Zilliqa-JavaScript-Library/issues/331.
By simulating a publish with Verdaccio, I found out that https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/332 doesn't work with a actual publish with lerna.
Simulated a publish with a local npm proxy registry using Verdaccio.
> fix: whitelist production files

- packages/zilliqa-js-core/package.json
- packages/zilliqa-js-subscriptions/package.json
This PR removes `crypto` and `util` dependencies in core package. It's because `crypto` and `util` packages are not used in the `core` package. Note the current dependency graph:
> build: remove unused pkg

- scripts/publish.ts
This PR removes the unused codes in `scripts/publish.ts` which have been unused since https://github.com/Zilliqa/Zilliqa-JavaScript-Library/commit/f2d8ea7d5bc9fccde5975defd69a230eeadf092d.
> refactor: remove unused codes

- packages/zilliqa-js-blockchain/src/chain.ts
- packages/zilliqa-js-blockchain/tsconfig.json
This PR 
- removes `contract` dep from `blockchain` by using `any` type instead and closes the #397.
- fixes the `zilliqa-js-crypto` ref in the tsconfig.
- solves subproblems of what https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/379 tried to solve.
References:
- https://github.com/Zilliqa/Zilliqa/pull/2728
- https://github.com/Zilliqa/dev-portal/pull/204
- https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/379
| Current Dependency Graph (v3.1.0) |
|:-:|
|![zil-js-dep-graph 001](https://user-images.githubusercontent.com/86328181/134621805-fb697d4d-b2f2-4461-9409-a098db1c8184.png)|
> feat(blockchain): remove contract dep

- packages/zilliqa-js-core/src/types.ts
This PR closes #396 by adding the `NumPages` which was missing.
Also it removes `Type` which shouldn't be included in the header.
References:
- https://dev.zilliqa.com/docs/apis/api-blockchain-get-tx-block#example-response
> fix(core): tx block header type

- packages/zilliqa-js-blockchain/src/chain.ts
This PR uses `isBlockNumber()` to remove redundancy.
> refactor: isBlockNumber

- package.json
This PR replaces `--exact` with `--force-publish=*` for `yarn release` since we want to unify the versions of packages at the moment.
References:
- https://github.com/lerna/lerna/tree/main/commands/version#--exact
- https://github.com/lerna/lerna/tree/main/commands/version#--force-publish
- https://github.com/lerna/lerna/tree/main/commands/publish#options
> chore: force publish

- .eslintrc.js
- packages/zilliqa-js-crypto/src/index.ts
- packages/zilliqa-js-crypto/src/random.ts
This PR prefers the newer ES6-style imports over require() by adding [no-require-imports](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-require-imports.md) rule and also prevents the issues like #422.
Also, to pass the CI this PR disables lint for the two existing require imports until all require imports are removed.
> chore(eslint): no-require-imports

- packages/zilliqa-js-crypto/src/schnorr.ts
- packages/zilliqa-js-crypto/src/signature.ts
- packages/zilliqa-js-crypto/test/schnorr.spec.ts
This PR closes #422. This reverts https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/386 with modifications.
References:
- https://github.com/Zilliqa/Zilliqa-JavaScript-Library/pull/386
- #411 
- #423 
- #426
- #412
- #416 
- #425
> fix: signature replacement

- packages/zilliqa-js-crypto/package.json
- packages/zilliqa-js-crypto/src/random.ts
- packages/zilliqa-js-crypto/test/random.node.spec.ts
- yarn.lock
This PR reverts #428 with modifications. 
If we use ES6 import syntax for sodium-native, in browsers it will throw an error `require is not defined`.
> fix: sodium-native

- packages/zilliqa-js-crypto/src/schnorr.ts
Years ago, zilliqa-js [included][1] my [schnorr] code in its codebase. I have no issues with that as it retained the proper copyright notice and attribution.
Unfortunately, every version of zilliqa-js distributed from [c274377][2] to [ed7704d][3] (the current HEAD) is in direct violation of the [license] for my [schnorr] project.
[c274377][2] removed the copyright notice after a refactor and rename, and [ed7704d][3] illegaly relicensed my code under the GPL3.
This PR adds the proper license and attribution. As the license holder, I refuse to have it relicensed as GPL, so you'll have to figure that out if you want to put your own attribution there.
On the condition that this is merged, you have my word that I will not pursue anything legally, but I would appreciate a public apology, maybe …
> Undo plagiarism of schnorr module
